### ISSUE TITLE
Client-side validation does not work

### ISSUE THREAD

**Issue by koxu1996** [justinvoelker/yii2-awesomebootstrapcheckbox#1]
Simple form:

```
echo $form = ActiveForm::begin(['id' => 'form-test', 'fieldClass' => 'justinvoelker\awesomebootstrapcheckbox\ActiveField',]); ?>
echo $form->field($model, 'terms')->checkbox() ?>
echo Html::submitButton('OK', ['class' => 'btn btn-primary', 'name' => 'ok-button']) ?>
echo ActiveForm::end();
```

and model rules:

```
[['terms'], 'required'],
[['terms'], 'required', 'requiredValue' => 1, 'message' => 'You must accept terms!']
```

result in checkbox with id **Test-terms-1**, but there is validator with another:

> jQuery('#form-test').yiiActiveForm([{**"id":"test-terms"**,"name":"terms","container":".field-test-terms","input":"#test-terms","error":".help-block.help-block-error","validate":function (attribute, value, messages, deferred, $form) {yii.validation.required(value, messages, {"message":"Terms can not be blank."});yii.validation.required(value, messages, {"message":"You must accept terms!","requiredValue":1});}}], []);

**Comment by justinvoelker** [comment]
Unfortunately, removing the value from the ID string means that in a checkbox list the IDs are duplicated. Barring a better solution, we can't incorporate this fix.

And really, something like a "terms and conditions" checkbox (which is what I guess you are discussing here) shouldn't absolutely need client-side validation. That would only come into play if someone checked the box then unchecked it. Even then, the form would still fail server-side validation so at least the form would not pass validation.

If you can come up with some that preserves unique IDs in a checkbox list and accomplishes your need I am willing to hear about it.
